<form action="<?=$this->url->get('messages/') ?>" id="mes_form" method="post">
	<input name="category" value="<?=$parse['category'] ?>" type="hidden">
	<div class="block">
		<div class="title">
			Сообщения
			<select name="messcat" onChange="$('#mes_form').submit()">
				<? foreach ($parse['types'] AS $type): ?>
					<option value="<?=$type ?>" <?=($type == $parse['category'] ? 'selected' : '') ?>><?=_getText('type', $type) ?></option>
				<? endforeach; ?>
			</select>
			по
			<select name="show_by" onChange="$('#mes_form').submit()">
				<? foreach ($parse['limit'] AS $limit): ?>
					<option value="<?=$limit ?>" <?=($limit == $parse['lim'] ? 'selected' : '') ?>><?=$limit ?></option>
				<? endforeach; ?>
			</select>
			на странице
			<div style="float: right">
				<input name="deletemessages" value="Удалить отмеченные" type="submit">
			</div>
		</div>
		<div class="content noborder">
			<table class="table">
				<tr>
					<th width="50"><input type="checkbox" onChange="SelectAll()" style='width:14px;'></th>
					<th width="150">Дата</th>
					<th>От</th>
					<th width="65">&nbsp;</th>
				</tr>
				<? foreach ($parse['list'] AS $list): ?>
					<tr>
						<th>
							<input name="showmes<?=$list['id'] ?>" type="hidden" value="1">
							<input name="delmes<?=$list['id'] ?>" type="checkbox" style='width:14px;'>
						</th>
						<th><?=$this->game->datezone("d.m.y H:i:s", $list['time']) ?></th>
						<th><a href="<?=$this->url->get('players/'.$list['sender'].'/') ?>" class="window popup-user"><?=$list['from'] ?></a></th>
						<th nowrap>
							<? if ($list['type'] == 1): ?>
								<a href="<?=$this->url->get('messages/write/'.$list['sender'].'/') ?>" title="Ответить"><span class='sprite skin_m'></span></a>
								&nbsp;<a href="<?=$this->url->get('messages/write/'.$list['sender'].'/quote/'.$list['id'].'/') ?>" title='Цитировать сообщение'><span class='sprite skin_z'></span></a>
								&nbsp;<a href="javascript:;" onclick='window.confirm("Вы уверены что хотите отправить жалобу на это сообщение?") ? window.location.href="<?=$this->url->get('messages/abuse/'.$list['id'].'/') ?>" : false;' title='Отправить жалобу'><span class='sprite skin_s'></span></a>
							<? else: ?>
								&nbsp;
							<? endif; ?>
						</th>
					</tr>
					<tr>
						<td style="background-color:<?=_getText('mess_background', $list['type']) ?>;" colspan="4" class="b">
							<? if ($list['type'] == 1 && $this->user->getUserOption('bb_parser')): ?>
								<span id="m<?=$list['id'] ?>"></span>
								<script type="text/javascript">Text('<?=str_replace(["\r\n", "\n", "\r"], '<br>', stripslashes($list['text'])) ?>', 'm<?=$list['id'] ?>');</script>
							<? else: ?>
								<?=stripslashes(nl2br($list['text'])) ?>
							<? endif; ?>
						</td>
					</tr>
				<? endforeach; ?>
				<? if (!count($parse['list'])): ?>
					<tr>
						<th colspan="4" align="center">нет сообщений</th>
					</tr>
				<? endif; ?>
			</table>
			<div style="float: left">
				<?=$parse['pages'] ?>
			</div>
			<div style="float: right;padding: 5px">
				<input name="deletemessages" value="Удалить отмеченные" type="submit">
			</div>
		</div>
	</div>
</form>