#!/usr/bin/env bash

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

/usr/local/bin/php /var/www/html/artisan migrate --seed
/usr/local/bin/php /var/www/html/artisan storage:link
chmod 777 /var/www/html/database/database.sqlite

exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf