<?php

namespace PHPSTORM_META
{
	override(\Phalcon\DiInterface::getShared(0),
			map([
				'' => '@',
				'url' => \Phalcon\Mvc\Url::class,
				'router' => \Phalcon\Mvc\Router::class,
				'db' => \Phalcon\Db\Adapter::class,
				'modelsManager' => \Phalcon\Mvc\Model\Manager::class,
				'modelsMetadata' => \Phalcon\Mvc\Model\MetaData::class,
				'cache' => \Phalcon\Cache\Backend::class,
				'session' => \Phalcon\Session\Adapter::class,
				'profiler' => \Fabfuel\Prophiler\Profiler::class,
				'crypt' => \Phalcon\Crypt::class,
				'annotations' => \Phalcon\Annotations\Adapter::class,
				'cookies' => \Phalcon\Http\Response\Cookies::class,
				'assets' => \Phalcon\Assets\Manager::class,
				'loader' => \Phalcon\Loader::class,
				'config' => \Phalcon\Config::class,
				'tag' => \Phalcon\Tag::class,
				'auth' => \Friday\Core\Auth\Auth::class,
				'view' => \Phalcon\Mvc\View\Simple::class,
				'user' => \Xnova\Models\User::class,
				'registry' => \Phalcon\Registry::class,
				'flashSession' => \Phalcon\Flash::class,
				'app' => \Phalcon\Application::class,
				'eventsManager' => \Phalcon\Events\Manager::class,
				'request' => \Phalcon\Http\Request::class,
				'response' => \Phalcon\Http\Response::class,
				'dispatcher' => \Phalcon\Dispatcher::class,
			]));

	override(\Phalcon\DiInterface::get(0),
			map([
				'' => '@',
				'url' => \Phalcon\Mvc\Url::class,
				'router' => \Phalcon\Mvc\Router::class,
				'db' => \Phalcon\Db\Adapter::class,
				'modelsManager' => \Phalcon\Mvc\Model\Manager::class,
				'modelsMetadata' => \Phalcon\Mvc\Model\MetaData::class,
				'cache' => \Phalcon\Cache\Backend::class,
				'session' => \Phalcon\Session\Adapter::class,
				'profiler' => \Fabfuel\Prophiler\Profiler::class,
				'crypt' => \Phalcon\Crypt::class,
				'annotations' => \Phalcon\Annotations\Adapter::class,
				'cookies' => \Phalcon\Http\Response\Cookies::class,
				'assets' => \Phalcon\Assets\Manager::class,
				'loader' => \Phalcon\Loader::class,
				'config' => \Phalcon\Config::class,
				'tag' => \Phalcon\Tag::class,
				'auth' => \Friday\Core\Auth\Auth::class,
				'view' => \Phalcon\Mvc\View\Simple::class,
				'user' => \Xnova\Models\User::class,
				'registry' => \Phalcon\Registry::class,
				'flashSession' => \Phalcon\Flash::class,
				'app' => \Phalcon\Application::class,
				'eventsManager' => \Phalcon\Events\Manager::class,
				'request' => \Phalcon\Http\Request::class,
				'response' => \Phalcon\Http\Response::class,
				'dispatcher' => \Phalcon\Dispatcher::class,
			]));
}