services:
  nginx:
    build: docker/nginx
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      NGINX_ENTRYPOINT_QUIET_LOGS: 1
    volumes:
      - ".:/home/www/app"
    depends_on:
      - nuxt
      - php
      - reverb
      - schedule

  nuxt:
    build: docker/frontend
    expose:
      - "3200"
    env_file:
      - docker/.env
    restart: unless-stopped

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: xnova
    restart: unless-stopped
    expose:
      - "9000"
    environment:
      TZ: "Europe/Moscow"
      APP_ENV: "example"
    volumes:
      - ".:/home/www/app"

  reverb:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    command: ["php", "/home/www/app/artisan", "reverb:start"]
    environment:
      TZ: "Europe/Moscow"
      APP_ENV: "example"
    volumes:
      - ".:/home/www/app"
    depends_on:
      - php

  schedule:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    command: ["php", "/home/www/app/artisan", "schedule:work"]
    environment:
      TZ: "Europe/Moscow"
      APP_ENV: "example"
    volumes:
      - ".:/home/www/app"
    depends_on:
      - php