<table class="table">
	<tr>
		<td class="c">Калькуляторы</td>
	</tr>
	<tr>
		<th><a href="<?=$this->url->get('calculate/cost/') ?>" data-link="1">Расчет строительства</a></th>
	</tr>
	<tr>
		<th><a href="<?=$this->url->get('calculate/fleet/') ?>" data-link="1">Расчет времени полёта</a></th>
	</tr>
	<tr>
		<th><a href="<?=$this->url->get('calculate/moon/') ?>" data-link="1">Расчет шанса уничтожения луны</a></th>
	</tr>
</table>