<table class="table">
	<tr>
		<td class="c col-sm-1 col-xs-1">Место</td>
		<td class="c col-sm-1 hidden-xs">+/-</td>
		<td class="c col-sm-4 col-xs-6">Игрок</td>
		<td class="c col-sm-1 col-xs-2">&nbsp;</td>
		<td class="c col-sm-3 hidden-xs">Альянс</td>
		<td class="c col-sm-2 col-xs-3">Очки</td>
	</tr>
	<? foreach ($stat AS $s): ?>
	<tr>
		<th class="th col-sm-1 col-xs-1">
			<?=$s['rank'] ?>
			<div class="visible-xs"><?=$s['rankplus'] ?></div>
		</th>
		<th class="th col-sm-1 hidden-xs"><?=$s['rankplus'] ?></th>
		<th class="th col-sm-4 col-xs-6">
			<a href="<?=$this->url->get('players/'.$s['id'].'/') ?>" class="window popup-user"><?=$s['name'] ?></a>
			<div class="visible-xs">
				<?=$s['alliance'] ?>
			</div>
		</th>
		<th class="th col-sm-1 col-xs-2">
			<? if ($s['race'] != 0): ?><img src="/assets/images/skin/race<?=$s['race'] ?>.gif" width="16" height="16" class="pull-left" style="margin-left:7px;"><? endif; ?>
			<? if (isset($userId) && $userId != 0): ?><?=$s['mes'] ?><? endif; ?>
		</th>
		<th class="th col-sm-3 hidden-xs"><?=$s['alliance'] ?></th>
		<th class="th col-sm-2 col-xs-3">
			<a href="<?=$this->url->get('players/stat/'.$s['id'].'/') ?>"><?=$s['points'] ?></a>
		</th>
	</tr>
	<? endforeach; ?>
</table>