<table class="table">
	<tr>
		<td class="c col-xs-1">Место</td>
		<td class="c col-xs-1">&nbsp;</td>
		<td class="c col-xs-4">Игроков</td>
		<td class="c col-xs-3">Очков</td>
		<td class="c col-xs-3">Очки на игрока</td>
	</tr>
	<? if (count($stat) > 0): ?>
		<? foreach ($stat AS $s): ?>
			<tr>
				<th><?=$s['rank'] ?></th>
				<th class="text-center"><img src="/assets/images/skin/race<?=$s['race'] ?>.gif" width="30" height="30"></th>
				<th><?=$s['count'] ?></th>
				<th><?=$s['points'] ?></th>
				<th><?=$s['pointatuser'] ?></th>
			</tr>
		<? endforeach; ?>
	<? endif; ?>
</table>