<form method="post" action="<?=$this->url->get('stat/') ?>" id="stats" class="hidden-xs-down">
	<input type="hidden" name="old_who" value="<?=$who ?>">
	<input type="hidden" name="old_type" value="<?=$type ?>">
	<table class="table">
		<tr>
			<td class="c" colspan="6">Статистика: <?=$update ?></td>
		</tr>
		<tr>
			<th width="15%" height="30">Какой</th>
			<th>
				<select name="who" onChange="$(this).parents('form').attr('action', <?=$this->url->get('stat/') ?>+'/'+$(this).val()+'/');$(this).parents('form').submit()" title="">
					<? foreach (_getText('who') AS $key => $value): ?>
						<option value="<?=$key ?>" <?=($key == $who ? 'selected' : '') ?>><?=$value ?></option>
					<? endforeach; ?>
				</select>
			</th>
			<th width="15%">по</th>
			<th>
				<select name="type" onChange="$(this).parents('form').submit()" title="">
					<? foreach (_getText('type') AS $key => $value): ?>
						<option value="<?=$key ?>" <?=($key == $type ? 'selected' : '') ?>><?=$value ?></option>
					<? endforeach; ?>
				</select>
			</th>
			<th width="15%">на месте</th>
			<th><select name="range" onChange="$(this).parents('form').submit()" title=""><?=$range ?></select></th>
		<tr>
	</table>
</form>
<form method="post" action="<?=$this->url->get('stat/') ?>" class="hidden-sm-up">
	<input type="hidden" name="old_who" value="<?=$who ?>">
	<input type="hidden" name="old_type" value="<?=$type ?>">
	<table class="table">
		<tr>
			<td class="c" colspan="4">Статистика: <?=$update ?></td>
		</tr>
		<tr>
			<th class="col-xs-2" height="30">Какой</th>
			<th class="col-xs-4">
				<select name="who" onChange="$(this).parents('form').attr('action', <?=$this->url->get('stat/') ?>+'/'+$(this).val()+'/');$(this).parents('form').submit()" title="">
					<? foreach (_getText('who') AS $key => $value): ?>
						<option value="<?=$key ?>" <?=($key == $who ? 'selected' : '') ?>><?=$value ?></option>
					<? endforeach; ?>
				</select>
			</th>
			<th class="col-xs-2">по</th>
			<th class="col-xs-4">
				<select name="type" onChange="$(this).parents('form').submit()" title="">
					<? foreach (_getText('type') AS $key => $value): ?>
						<option value="<?=$key ?>" <?=($key == $type ? 'selected' : '') ?>><?=$value ?></option>
					<? endforeach; ?>
				</select>
			</th>
		</tr>
		<tr>
			<th></th>
			<th></th>
			<th class="col-xs-2">на месте</th>
			<th class="col-xs-10"><select name="range" onChange="$(this).parents('form').submit()" title=""><?=$range ?></select></th>
		<tr>
	</table>
</form>
<div class="separator"></div>