<div class="portlet box green">
	<div class="portlet-title">
		<div class="caption">Глобальные настройки сервера</div>
	</div>
	<div class="portlet-body form">
		<form action="/admin/settings/" method="post" class="form-horizontal form-bordered">
			<input type="hidden" name="save" value="Y">
			<div class="form-body">
				<? foreach ($parse['settings'] AS $setting): ?>
					<div class="form-group">
						<label class="col-md-3 control-label"><?=$setting['key'] ?></label>
						<div class="col-md-9">
							<? if ($setting['type'] == 'textarea'): ?>
								<textarea rows="5" name="setting[<?=$setting['key'] ?>]" class="form-control"><?=$setting['value'] ?></textarea>
							<? else: ?>
								<input name="setting[<?=$setting['key'] ?>]" value="<?=$setting['value'] ?>" type="text" class="form-control">
							<? endif; ?>
						</div>
					</div>
				<? endforeach; ?>
				<div class="form-actions">
					<button type="submit" class="btn green">Сохранить</button>
				</div>
			</div>
		</form>
	</div>
</div>