<?
/**
 * @var $planetlist array
 * @var $all integer
 * @var $pagination string
 */
?>
<div class="util-btn-margin-bottom-5">
	<a href="<?=$this->url->get('admin/planetlist/mode/add/') ?>">
		<button type="button" class="btn blue btn-sm">Создать</button>
	</a>
</div>
<div class="clearfix"></div>
<div class="table-responsive">
	<table class="table table-striped table-hover table-advance">
		<thead>
			<tr>
				<th width="50">ID</th>
				<th>Название планеты</th>
				<th>Галактика</th>
				<th>Система</th>
				<th>Планета</th>
				<th>Переход</th>
			</tr>
		</thead>
		<? foreach ($planetlist AS $planet): ?>
			<tr>
				<td class="b center"><?=$planet['id'] ?></td>
				<td class="b center"><?=$planet['name'] ?></td>
				<td class="b center"><?=$planet['galaxy'] ?></td>
				<td class="b center"><?=$planet['system'] ?></td>
				<td class="b center"><?=$planet['planet'] ?></td>
				<td class="b center"><?=\App\Helpers::BuildPlanetAdressLink($planet) ?></td>
			</tr>
		<? endforeach; ?>
	</table>
</div>
<div class="row">
	<div class="col-md-5 col-sm-12">
		<div class="dataTables_info">
			В игре <b><?=$all ?></b> планет<?=\App\Helpers::morph($all, 'feminine', 5) ?>
		</div>
	</div>
	<div class="col-md-7 col-sm-12">
		<div class="dataTables_paginate paging_bootstrap">
			<?=$pagination ?>
		</div>
	</div>
</div>