<div class="table-responsive">
	<table class="table table-striped table-hover table-advance">
		<thead>
			<tr>
				<th width="50">ID</th>
				<th width="20%">Игрок</th>
				<th>Тема</th>
				<th width="150">Статус</th>
				<th width="150">Дата</th>
			</tr>
		</thead>
		<? foreach ($tickets['open'] AS $list): ?>
		<tr>
			<td><?=$list['id'] ?></td>
			<td><?=$list['username'] ?></td>
			<td><a href="/admin/support/mode/detail/id/<?=$list['id'] ?>/"><?=$list['subject'] ?></a></td>
			<td><?=$list['status'] ?></td>
			<td><?=$list['date'] ?></td>
		</tr>
		<? endforeach; ?>
		<? if (count($tickets['open']) == 0): ?>
			<th colspan="5" class="c">Нет новых запросов</th>
		<? endif; ?>
	</table>
</div>
<? if (!empty($tickets['closed'])): ?>
<br><br>
<table class="table">
	<tr>
		<td colspan="5" class="c text-xs-center">
			Служба техподдержки
		</td>
	</tr>
	<tr>
		<td class="c text-xs-center" width="10%">
			ID
		</td>
		<td class="c text-xs-center" width="10%">
			Игрок
		</td>
		<td class="c text-xs-center" width="40%">
			Тема
		</td>
		<td class="c text-xs-center" width="15%">
			Статус
		</td>
		<td class="c text-xs-center" width="25%">
			Дата
		</td>
	</tr>
	<? foreach ($tickets['closed'] AS $list): ?>
	<tr>
		<th><?=$list['id'] ?></th>
		<th><?=$list['username'] ?></th>
		<th><a href="/admin/support/mode/detail/id/<?=$list['id'] ?>/"><?=$list['subject'] ?></a></th>
		<th><?=$list['status'] ?></th>
		<th><?=$list['date'] ?></th>
	</tr>
	<? endforeach; ?>
</table>
<? endif; ?>
<? if (isset($parse['t_id'])): ?>
	<br><br>
	<table class="table table-advance">
		<thead>
			<tr>
				<th width="50">
					<center>ID</center>
				</th>
				<th width="20%">
					<center>Игрок</center>
				</th>
				<th>
					<center>Тема</center>
				</th>
				<th width="150">
					<center>Статус</center>
				</th>
				<th width="150">
					<center>Дата</center>
				</th>
			</tr>
		</thead>
		<tr>
			<td><?=$parse['t_id'] ?></td>
			<td><?=$parse['t_username'] ?></td>
			<td><?=$parse['t_subject'] ?></a></td>
			<td><?=$parse['t_statustext'] ?></td>
			<td><?=$parse['t_date'] ?></td>
		</tr>
	</table>
	<div class="separator"></div>
	<table class="table table-advance">
		<thead>
			<tr>
				<th>Текст запроса:</th>
			</tr>
		</thead>
		<tr>
			<td><?=$parse['t_text'] ?></td>
		</tr>
	</table>
	<div class="portlet box green">
		<div class="portlet-title">
			<div class="caption">Ответ</div>
		</div>
		<div class="portlet-body form">
			<form action="/admin/support/mode/send/id/<?=$parse['t_id'] ?>/" method="POST">
				<div class="form-body">
					<div class="form-group">
						<textarea class="form-control" rows="10" name="text" title=""></textarea>
					</div>
					<div class="form-actions">
						<button type="submit" class="btn green">Ответить</button>
					</div>
				</div>
			</form>
			<hr>
			<? if ($parse['t_status'] != 0): ?>
			<form action="/admin/support/mode/close/id/<?=$parse['t_id'] ?>/" method="POST">
				<input type="submit" value="Закрыть"></form>
			<? else: ?>
			<form action="/admin/support/mode/open/id/<?=$parse['t_id'] ?>/" method="POST">
				<input type="submit" value="Открыть"></form>
			<? endif; ?>
		</div>
	</div>
<? endif; ?>