<? if ($this->config->view->get('socialIframeView', 0) && $_SERVER['SERVER_NAME'] == 'ok1.xnova.su'): ?>
	<script type="text/javascript">
		var title = [];
		title[0] = "Звездная империя – космическая стратегия в реальном времени.";
		title[1] = "Звездная империя - отличная космическая войнушка.";
		title[2] = "Звездная империя - интересная игра, приглашаю стать моим союзником.";
		title[3] = "Отстраивай планету и повышай свой рейтинг";
		title[4] = "Ищу союзников, для серьезных дел.";
		title[5] = "Игра затягивает! Советую!";
		title[6] = "Друзья, помогите мне с победой. Спасибо!";
		title[7] = "Пришло время воевать!";

		function showInviteBox ()
		{
			var text = title[Math.round(Math.random()*7)];

			FAPI.UI.showInvite(text, 'userId=<?=$this->user->getId() ?>');
		}
	</script>
<? endif; ?>
<a href="#" class="menu-toggle visible-xs">
    <span>
        <span class="first"></span>
        <span class="second"></span>
        <span class="third"></span>
    </span>
</a>
<div class="menu-sidebar visible-xs">
	<ul class="nav">
		<? foreach(_getText('main_menu') AS $id => $menu): if ($menu[2] > $adminlevel) continue; ?>
			<li><a data-link="<?=$id ?>" <? if (isset($menu[3])): ?>data-link="Y"<? endif; ?> href="<?=$menu[1] ?>" <?=($controller == $id ? 'class="check"' : '') ?>><?=$menu[0] ?></a></li>
		<? endforeach; ?>
	</ul>
</div>
<div class="contentBox set_<?=$controller ?>">
	<div id="box">
		<div class="game_menu">
			<div class="visible-xs text-center bar">
				<? if (isset($tutorial) && $tutorial < 10): ?>
					<a class="m1 tooltip" href="<?=$this->url->get("tutorial/") ?>" data-tooltip-content="Квесты"><span class="sprite ico_tutorial"></span></a>
				<? endif; ?>
				<a class="m1 tooltip" href="<?=$this->url->get("chat/") ?>" data-tooltip-content="Чат"><span class="sprite ico_chat"></span></a>
				<a class="m1 tooltip" href="<?=$this->url->get("messages/") ?>" data-tooltip-content="Сообщения"><span class="sprite ico_mail"></span> <b><?=$messages ?></b></a>
				<? if ($messages_ally != ''): ?>
					<a class="m1 tooltip" href="<?=$this->url->get("alliance/chat/") ?>" data-tooltip-content="Альянс"><span class="sprite ico_alliance"></span> <b><?=$messages_ally ?></b></a>
				<? endif; ?>
			</div>
			<div class="bar hhh hidden-xs">
				<div class="message_list">
					<? if (isset($tutorial) && $tutorial < 10): ?>
						<a class="m1 tooltip" href="<?=$this->url->get("tutorial/") ?>" data-tooltip-content="Квесты"><span class="sprite ico_tutorial"></span></a>
					<? endif; ?>
					<a class="m1 tooltip" href="<?=$this->url->get("chat/") ?>" data-tooltip-content="Чат"><span class="sprite ico_chat"></span></a>
					<a class="m1 tooltip" href="<?=$this->url->get("messages/") ?>" data-tooltip-content="Сообщения"><span class="sprite ico_mail"></span> <b id="new_messages"><?=$messages ?></b></a>
					<? if ($messages_ally != ''): ?>
						<a class="m1 tooltip" href="<?=$this->url->get('alliance/chat/') ?>" data-tooltip-content="Альянс"><span class="sprite ico_alliance"></span> <b id="ally_messages"><?=$messages_ally ?></b></a>
					<? endif; ?>
				</div>
				<table align="center" class="top_menu">
					<tr>
						<? if ($this->config->view->get('socialIframeView', 0)): ?>
							<td class="m1"><a href="?fullscreen=Y" target="_blank" class="tooltip sprite ico_fullscreen" data-tooltip-content="Развернуть"></a></td>
						<? endif; ?>
						<? if (!$this->config->view->get('socialIframeView', 0)): ?>
							<td class="m1"><a href="http://xnova.su/" target="_blank" class="tooltip sprite ico_space" data-tooltip-content="Вселенные"></a></td>
						<? endif; ?>
						<td class="m1"><a href="<?=$this->url->get("stat/") ?>" class="tooltip sprite ico_stats" data-tooltip-content="Статистика"></a></td>
						<td class="m1"><a href="<?=$this->url->get("tech/") ?>" class="tooltip sprite ico_tech" data-tooltip-content="Технологии"></a>
						<td class="m1"><a href="<?=$this->url->get("sim/") ?>" class="tooltip sprite ico_sim" data-tooltip-content="Симулятор"></a>
						<td class="m1"><a href="<?=$this->url->get("search/") ?>" class="tooltip sprite ico_search" data-tooltip-content="Поиск"></a></td>
						<? if ($this->config->view->get('socialIframeView', 0) == 0): ?>
							<td class="m1"><a href="<?=$this->url->get("support/") ?>" class="tooltip sprite ico_support" data-tooltip-content="Техподдержка"></a></td>
						<? endif; ?>
						<? if ($this->config->view->get('socialIframeView', 0) == 0): ?>
							<td class="m1"><a href="<?=$this->config->game->get('forum_url', '') ?>" target="_blank" class="tooltip sprite ico_forum" data-tooltip-content="Форум"></a></td>
						<? endif; ?>
						<td class="m1"><a href="<?=$this->url->get("options/") ?>" class="tooltip sprite ico_settings" data-tooltip-content="Настройки"></a></td>
						<? if ($this->config->view->get('socialIframeView', 0) == 0): ?>
							<td class="m1"><a href="<?=$this->url->get("logout/") ?>" class="tooltip sprite ico_exit" data-tooltip-content="Выход"></a></td>
						<? endif; ?>
						<? if ($this->config->view->get('socialIframeView', 0) && $_SERVER['SERVER_NAME'] == 'ok1.xnova.su'): ?>
							<? if (!$this->cookies->has($this->config->cookie->prefix.'_full')): ?>
								<td class="m1" style="vertical-align: middle"><a style="color:#38CA38" href="javascript:;" onclick="showInviteBox()">Пригласить друзей</a></td>
							<? endif; ?>
						<? endif; ?>
					</tr>
				</table>
			</div>
		</div>
		<div class="icon-panel visible-xs">
			<a href="<?=$this->url->get("stat/") ?>" class="sprite ico_stats"></a>
			<a href="<?=$this->url->get("tech/") ?>" class="sprite ico_tech"></a>
			<a href="<?=$this->url->get("sim/") ?>" class="sprite ico_sim"></a>
			<a href="<?=$this->url->get("search/") ?>" class="sprite ico_search"></a>
			<a href="<?=$this->url->get("support/") ?>" class="sprite ico_support"></a>
			<a href="<?=$this->config->game->get('forum_url', '') ?>" target="_blank" class="sprite ico_forum"></a>
			<a href="<?=$this->url->get("options/") ?>" class="sprite ico_settings"></a>
			<a href="<?=$this->url->get("logout/") ?>" class="sprite ico_exit"></a>
		</div>
		<div class="game_content">
			<ul class="menu hidden-xs">
				<? foreach(_getText('main_menu') AS $id => $menu): if ($menu[2] > $adminlevel) continue; ?>
					<li><a id="link_<?=$id ?>" <? if (isset($menu[3])): ?>data-link="Y"<? endif; ?> href="<?=$menu[1] ?>" <?=($controller == $id ? 'class="check"' : '') ?>><?=$menu[0] ?></a></li>
				<? endforeach; ?>
			</ul>
			<? if ($this->config->view->get('overviewListView', 0) == 1): ?>
				<? $this->partial('shared/planets'); ?>
			<? endif; ?>
			<div class="content">
				<? if ($this->config->view->get('socialIframeView', 0) == 1): ?>
					<div class="iframe_wrapper">
				<? endif; ?>
				<div id="gamediv" class="container-fluid">