<? if ($_SERVER['SERVER_NAME'] == 'vk.xnova.su'): ?>
	<script src="//vk.com/js/api/xd_connection.js" type="text/javascript"></script>
	<script type="application/javascript">
		$(window).load(function()
		{
			  VK.init(function() { console.log('vk init success'); }, function() {}, '5.24');
		});
	</script>
<? endif; ?>

<?
	if ($this->request->has('apiconnection') && (!$this->session->has('OKAPI') || !isset($this->session->get('OKAPI')['apiconnection'])))
	{
		$_SESSION['OKAPI'] = Array
		(
			'api_server' 			=> $this->request->get('api_server'),
			'apiconnection' 		=> $this->request->get('apiconnection'),
			'session_secret_key' 	=> $this->request->get('session_secret_key'),
			'session_key' 			=> $this->request->get('session_key'),
			'logged_user_id' 		=> $this->request->get('logged_user_id'),
			'sig' 					=> $this->request->get('sig')
		);
	}
?>
<? if (!$this->cookies->has($this->config->cookie->prefix.'_full') && $this->session->has('OKAPI') && is_array($this->session->get('OKAPI'))): ?>
	<script src="<?=$this->session->get('OKAPI')['api_server'] ?>js/fapi5.js" type="text/javascript"></script>
	<script type="text/javascript">
		FAPI.init('<?=$this->session->get('OKAPI')['api_server'] ?>', '<?=$this->session->get('OKAPI')['apiconnection'] ?>',
			function()
			{
				//FAPI.UI.setWindowSize(800, 700);
			}
			, function()
			{
				alert("API initialization failed");
			}
		);
	</script>
<? endif; ?>