<?
/**
 * @var $who string
 * @var $type string
 * @var $update string
 */
?>
<form method="post" action="<?=$this->url->get('stat/') ?>" id="stats">
	<input type="hidden" name="old_who" value="<?=$who ?>">
	<input type="hidden" name="old_type" value="<?=$type ?>">
	<div class="table">
		<div class="row">
			<div class="c col-xs-12">Статистика: <?=$update ?></div>
		</div>
		<div class="row">
			<div class="th col-xs-2 middle">Какой</div>
			<div class="th col-xs-4 col-sm-2">
				<select name="who" onChange="$(this).parents('form').attr('action', <?=$this->url->get('stat/') ?>+$(this).val()+'/');$(this).parents('form').submit()" title="">
					<? foreach (_getText('who') AS $key => $value): ?>
						<option value="<?=$key ?>" <?=($key == $who ? 'selected' : '') ?>><?=$value ?></option>
					<? endforeach; ?>
				</select>
			</div>
			<div class="th col-xs-2 col-sm-1 middle">по</div>
			<div class="th col-xs-4 col-sm-3">
				<select name="type" onChange="$(this).parents('form').submit()" title="">
					<? foreach (_getText('type') AS $key => $value): ?>
						<option value="<?=$key ?>" <?=($key == $type ? 'selected' : '') ?>><?=$value ?></option>
					<? endforeach; ?>
				</select>
			</div>
			<div class="th col-xs-2 middle hidden-xs-down">на месте</div>
			<div class="th col-xs-10 col-sm-2 hidden-xs-down"><select name="range" onChange="$(this).parents('form').submit()" title=""><?=$range ?></select></div>
		</div>
		<div class="row hidden-sm-up">
			<div class="th col-xs-2 middle">на месте</div>
			<div class="th col-xs-10"><select name="range" onChange="$(this).parents('form').submit()" title=""><?=$range ?></select></div>
		</div>
	</div>
</form>
<div class="separator"></div>