<table class="table">
	<tr>
		<td class="c">Управление альянсом</td>
	</tr>
	<? if ($this->user->isAdmin() && $parse['owner'] == $userId): ?>
		<tr>
			<th><a href="<?=$this->url->get('alliance/admin/edit/planets/') ?>">Планеты альянса</a></th>
		</tr>
	<? endif; ?>
	<tr>
		<th><a href="<?=$this->url->get('alliance/admin/edit/rights/') ?>">Установить ранги</a></th>
	</tr>
	<tr>
		<th><a href="<?=$this->url->get('alliance/admin/edit/members/') ?>">Члены альянса</a></th>
	</tr>
	<tr>
		<th><a href="<?=$this->url->get('alliance/admin/edit/tag/') ?>">Изменить аббревиатуру альянса</a></th>
	</tr>
	<tr>
		<th><a href="<?=$this->url->get('alliance/admin/edit/name/') ?>">Изменить название альянса</a></th>
	</tr>
</table>

<form action="<?=$this->url->get('alliance/admin/edit/ally/t/'.$parse['t'].'/') ?>" method="POST">
	<input type="hidden" name="t" value="<?=$parse['t'] ?>">
	<table class="table">
		<tr>
			<td class="c" colspan="3"><?=_getText('Texts') ?></td>
		</tr>
		<tr>
			<th><a href="<?=$this->url->get('alliance/admin/edit/ally/t/1/') ?>">Внешний текст</a></th>
			<th><a href="<?=$this->url->get('alliance/admin/edit/ally/t/2/') ?>">Внутренний текст</a></th>
			<th><a href="<?=$this->url->get('alliance/admin/edit/ally/t/3/') ?>">Текст заявки</a></th>
		</tr>
		<tr>
			<td class="c" colspan="3"><?=_getText('Show_of_request_text') ?></td>
		</tr>
		<tr>
			<th colspan="3" class="nopadding">
				<div id="editor"></div>
				<script type="text/javascript">edToolbar('text');</script>
				<textarea name="text" id="text" rows="15"><?=preg_replace('!<br.*>!iU', "\n", $parse['text']) ?></textarea>
			</th>
		</tr>
		<tr>
			<th colspan="3"><input type="reset" value="Очистить"><input type="submit" value="Сохранить"></th>
		</tr>
	</table>
	<div id="showpanel" style="display:none">
		<table align="center" class="table">
			<tr>
				<td class="c"><b>Предварительный просмотр</b></td>
			</tr>
			<tr>
				<td class="b" style="padding:3px;"><span id="showbox"></span></td>
			</tr>
		</table>
	</div>
</form>

<form action="<?=$this->url->get('alliance/admin/edit/ally/') ?>" method="POST">
	<table class="table">
		<tr>
			<td class="c" colspan="2">Дополнительные настройки</td>
		</tr>
		<tr>
			<th width="150">Домашняя страница</th>
			<th><input type="text" name="web" value="<?=$parse['web'] ?>" style="width:98%;"></th>
		</tr>
		<tr>
			<th>Логотип</th>
			<th><input type="text" name="image" value="<?=$parse['image'] ?>" style="width:98%;"></th>
		</tr>
		<tr>
			<th>Ранг основателя</th>
			<th><input type="text" name="owner_range" value="<?=$parse['owner_range'] ?>" style="width:98%;"></th>
		</tr>
		<tr>
			<th>Заявки</th>
			<th>
				<select style="width:98%;" name="request_notallow">
					<option value=1<?=$parse['request_notallow_0'] ?>><?=_getText('No_allow_request') ?></option>
					<option value=0<?=$parse['request_notallow_1'] ?>><?=_getText('Allow_request') ?></option>
				</select>
			</th>
		</tr>
		<tr>
			<th colspan="2"><input type="submit" name="options" value="Сохранить"></th>
		</tr>
	</table>
</form>

<table class="table">
	<tr>
		<td width="50%">
			<?=$parse['Disolve_alliance'] ?>
		</td>
		<td>
			<?=$parse['Transfer_alliance'] ?>
		</td>
	</tr>
</table>

