<table class="table" style="table-layout: fixed;">
	<tr>
		<td class=c colspan=2>Информация об альянсе</td>
	</tr>
	<?=$parse['image'] ?>
	<tr>
		<th>Аббревиатура</th>
		<th><?=$parse['tag'] ?></th>
	</tr>
	<tr>
		<th>Название</th>
		<th><?=$parse['name'] ?></th>
	</tr>
	<tr>
		<th>Члены альянса</th>
		<th><?=$parse['members'] ?><?=$parse['members_list'] ?></th>
	</tr>
	<tr>
		<th>Ваш ранг</th>
		<th><?=$parse['range'] ?> <?=$parse['alliance_admin'] ?></th>
	</tr>
	<? if (isset($parse['diplomacy'])): ?>
		<tr>
			<th>Дипломатия</th>
			<th><?=$parse['diplomacy'] ?></th>
		</tr>
	<? endif; ?>
	<?=$parse['requests'] ?>
	<?=$parse['send_circular_mail'] ?>
	<tr>
		<td class="b" colspan="2" height="100" style="padding:3px;">
			<span id="m1"></span>
		</td>
	</tr>
	<? if ($parse['web']): ?>
		<tr>
			<th>Домашняя страница</th>
			<th><a href="<?=$parse['web'] ?>" target="_blank"><?=$parse['web'] ?></a></th>
		</tr>
	<? endif; ?>
	<tr>
		<td class=c colspan=2>Внутренняя компетенция</td>
	</tr>
	<tr>
		<td class="b" colspan="2" height="100" style="padding:3px;">
			<span id="m2"></span>
		</td>
	</tr>
	<? if ($parse['owner'] != ''): ?>
	<tr>
		<td colspan="2">
			<?=$parse['owner'] ?>
		</td>
	</tr>
	<? endif; ?>
</table>
<script>
	Text('<?=str_replace(array("\r\n", "\n", "\r"), '', stripslashes($parse['description'])) ?>', 'm1');
	Text('<?=str_replace(array("\r\n", "\n", "\r"), '', stripslashes($parse['text'])) ?>', 'm2');
</script>