<table class="table" style="table-layout: fixed;">
	<tr>
		<td class="c" colspan="2">Информация об альянсе</td>
	</tr>
	<?=$parse['image'] ?>
	<tr>
		<th><?=_getText('Tag') ?></th>
		<th><?=$parse['tag'] ?></th>
	</tr>
	<tr>
		<th><?=_getText('Name') ?></th>
		<th><?=$parse['name'] ?></th>
	</tr>
	<tr>
		<th><?=_getText('Members') ?></th>
		<th><?=$parse['member_scount'] ?></th>
	</tr>
	<tr>
		<td class="b" colspan="2" height="100" style="padding:3px;"><span id="m1"></span></td>
	</tr>

	<?=$parse['web'] ?>

	<? if (isset($userId) && $userId != 0): ?><?= $parse['bewerbung'] ?><? endif; ?>
</table>
<script>Text('<?=str_replace(array("\r\n", "\n", "\r"), '', stripslashes($parse['description'])) ?>', 'm1');</script>