<form action="<?=$this->url->get('alliance/search/') ?>" method="POST">
	<table class="table">
		<tr>
			<td class="c" colspan="2">Поиск альянса</td>
		</tr>
		<tr>
			<th>Строка поиска</th>
			<th>
				<input type="text" name="searchtext" value="<?=$parse['searchtext'] ?>"><input type="submit" value="Поиск">
			</th>
		</tr>
	</table>
</form>

<? if (count($parse['result']) > 0): ?>
	<div class="separator"></div>
	<table class="table">
		<tr>
			<td class=c colspan=3>Найденые альянсы:</td>
		</tr>
		<? foreach ($parse['result'] AS $r): ?>
		<tr>
			<th>
				<center><?=$r['ally_tag'] ?></center>
			</th>
			<th>
				<center><?=$r['ally_name'] ?></center>
			</th>
			<th>
				<center><?=$r['ally_members'] ?></center>
			</th>
		</tr>
		<? endforeach; ?>
		<tr>
	</table>
<? endif; ?>
