<?= $this->tag->getDoctype() ?>
<html lang="ru">
<head>
	<?php echo $this->tag->getTitle(); ?>
	<?= $this->tag->tagHtml('meta', ['name' => 'description', 'content' => '']) ?>
	<?= $this->tag->tagHtml('meta', ['name' => 'keywords', 'content' => '']) ?>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">

	<link rel="image_src" href="http://<?=$_SERVER['HTTP_HOST'] ?>/assets/images/logo.jpg" />
	<link rel="apple-touch-icon" href="http://<?=$_SERVER['HTTP_HOST'] ?>/assets/images/apple-touch-icon.png"/>

	<?php $this->assets->outputJs('js') ?>
	<?php $this->assets->outputCss('css') ?>
</head>
<body class="<? if ($this->config->view->get('socialIframeView', 0) == 1): ?>iframe<? else: ?>window<? endif; ?>">
	<div id="box" class="set_error">
		<? if (isset($leftMenu) && $leftMenu == true): ?>
			<? $this->partial('shared/header'); ?>
		<? endif; ?>
		<div class="game_content">
			<? if (isset($leftMenu) && $leftMenu == true): ?>
				<? $this->partial('shared/menu'); ?>
			<? endif; ?>
			<div id="gamediv" class="content container-fluid">
				<div class="row">
					<div class="e404">404</div>
				</div>
			</div>
		</div>
	</div>
</body>
</html>