<?= $this->tag->getDoctype() ?>
<html lang="ru">
<head>
	<?php echo $this->tag->getTitle(); ?>
	<?= $this->tag->tagHtml('meta', ['name' => 'description', 'content' => '']) ?>
	<?= $this->tag->tagHtml('meta', ['name' => 'keywords', 'content' => '']) ?>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">

	<link rel="image_src" href="http://<?=$_SERVER['HTTP_HOST'] ?>/assets/images/logo.jpg" />
	<link rel="apple-touch-icon" href="http://<?=$_SERVER['HTTP_HOST'] ?>/assets/images/apple-touch-icon.png"/>

	<?php $this->assets->outputJs('headerJs') ?>
	<?php $this->assets->outputCss('headerCss') ?>

	<? if (!function_exists('allowMobileVersion') || !allowMobileVersion()): ?>
		<meta name="viewport" content="width=810">
	<? else: ?>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<script type="text/javascript">
			$(document).ready(function()
			{
				$("body").swipe(
				{
					swipeLeft: function()
					{
						if ($('.menu-sidebar').hasClass('opened'))
							$('.menu-toggle').click();
						else
							$('.planet-toggle').click();
					},
					swipeRight: function()
					{
						if ($('.planet-sidebar').hasClass('opened'))
							$('.planet-toggle').click();
						else
							$('.menu-toggle').click();
					},
					threshold: 100,
					excludedElements: ".table-responsive",
					fallbackToMouseEvents: false,
					allowPageScroll: "auto"
				});
			});
		</script>
	<? endif; ?>
</head>
<body class="<? if ($this->config->view->get('socialIframeView', 0) == 1): ?>iframe<? else: ?>window<? endif; ?>">
	<script type="text/javascript">
		XNova.path = '/';
		var timestamp = <?=time() ?>;
		var timezone = <?=$timezone ?>;
		var ajax_nav = <?=$this->config->app->ajaxNavigation ?>;
		var addToUrl = '<? if (!$this->cookies->has($this->config->cookie->prefix.'_full') && $this->session->has('OKAPI')): ?><?=http_build_query($this->session->get('OKAPI')) ?><? endif; ?>';

		<? if ($this->auth->isAuthorized()): ?>
			XNova.fleetSpeed 	= <?=$this->game->getSpeed('fleet') ?>;
			XNova.gameSpeed 	= <?=round($this->config->game->get('game_speed', 1) / 2500, 1) ?>;
			XNova.resSpeed 		= <?=$this->config->game->get('resource_multiplier', 1) ?>;
		<? endif; ?>
	</script>
	<? if (isset($leftMenu) && $leftMenu == true): ?>
		<? $this->partial('shared/menu'); ?>
	<? endif; ?>

	<? if (isset($topPanel) && $topPanel == true): ?>
		<? $this->partial('shared/panel'); ?>
	<? endif; ?>

	<? if (!isset($leftMenu) || $leftMenu == false): ?>
		<div class="contentBox"><div><div id="box"><center>
	<? endif; ?>


	<? if (isset($pageParams['deleteUserTimer']) && $pageParams['deleteUserTimer'] > 0): ?>
		<table class="table"><tr><td class="c" align="center">Включен режим удаления профиля!<br>Ваш аккаунт будет удалён после <?=datezone("d.m.Y", $pageParams['deleteUserTimer']) ?> в <?=datezone("H:i:s", $pageParams['deleteUserTimer']) ?>. Выключить режим удаления можно в настройках игры.</td></tr></table><div class="separator"></div>
	<? endif; ?>

	<? if (isset($pageParams['vocationTimer']) && $pageParams['vocationTimer'] > 0): ?>
	   <table class="table"><tr><td class="c" align="center"><font color="red">Включен режим отпуска! Функциональность игры ограничена.</font></td></tr></table><div class="separator"></div>
	<? endif; ?>

	<? if (isset($pageParams['message']) && $pageParams['message'] != ''): ?>
	   <table class="table"><tr><td class="c" align="center"><?=$pageParams['message'] ?></td></tr></table><div class="separator"></div>
	<? endif; ?>

	<div class="row">
		<? if (isset($html) && isset($html_position) && $html_position == 'top'): ?>
			<?=$html ?>
		<? endif; ?>

		<?php echo $this->getContent() ?>

		<? if (isset($html) && (!isset($html_position) || $html_position == 'bottom')): ?>
			<?=$html ?>
		<? endif; ?>
	</div>

	<? if (isset($leftMenu) && $leftMenu == true): ?>
		</div>

		<div id="loadingOverlay">загрузка...<br><img src="/assets/images/loading.gif" alt=""></div>
		<div id="preloadOverlay"><img src="/assets/images/loading.gif" alt=""></div>

		<? if ($this->config->view->get('socialIframeView', 0) == 1): ?>
			</div>
		<? endif; ?>
		</div>
		<div class="clearfix"></div>
		</div>
		</div>
		</div></div>

		<div id="siteFooter" class="hidden-xs">
			<div class="container-fluid">
				<div class="pull-left text-left">
					<a href="?set=news" title="Последние изменения">000</a>
					<? if ($this->config->view->get('socialIframeView', 0) == 0): ?>
						<a class="hidden-sm" target="_blank" href="http://xnova.su/">© 2008 - <?=date("Y") ?> Xcms</a>
					<? endif; ?>
				</div>
				<div class="pull-right text-right">
					<? if ($this->config->view->get('socialIframeView', 0) == 1): ?>
						<a href="http://www.odnoklassniki.ru/group/56711983595558" class="ok" target="_blank">Группа игры</a>|
					<? endif; ?>
					<a href="http://forum.xnova.su/" target="_blank">Форум</a>|
					<a href="?set=banned">Тёмные</a>|
					<? if ($this->config->view->get('socialIframeView', 0) == 0): ?>
						<a href="/wide.php" data-link="1">Большой монитор</a>|
						<a href="http://vk.com/xnova_game" target="_blank">ВК</a>|
						<a href="?set=contact">Контакты</a>|
					<? endif;?>
					<a href="?set=content&article=help">Новичкам</a>|
					<a href="?set=content&article=agb">Правила</a>|
					<a onclick="" title="Игроков в сети" style="color:green"><?=$this->config->app->get('online') ?></a>/<a onclick="" title="Всего игроков" style="color:yellow"><?=$this->config->app->get('users_amount') ?></a>
				</div>
				<br class="clearfloat"/></div>
		</div>
		<div class="row hidden-sm hidden-md hidden-lg footer-mobile">
			<div class="col-xs-12 text-center">
				<a href="http://forum.xnova.su/" target="_blank">Форум</a>|
				<a href="?set=banned">Тёмные</a>|
				<a href="?set=contact">Контакты</a>|
				<a href="?set=content&article=help">Новичкам</a>|
				<a href="?set=content&article=agb">Правила</a>
			</div>
			<div class="col-xs-8 text-center">
				<a href="?set=news" title="Последние изменения">000</a>
				<? if ($this->config->view->get('socialIframeView', 0) == 0): ?>
					<a class="media_1" target="_blank" href="http://xnova.su/">© 2008 - <?=date("Y") ?> Xcms</a>
				<? endif; ?>
			</div>
			<div class="col-xs-4 text-center">
				<a onclick="" title="Игроков в сети" style="color:green"><?=$this->config->app->get('online') ?></a>/<a onclick="" title="Всего игроков" style="color:yellow"><?=$this->config->app->get('users_amount') ?></a>
			</div>
		</div>
	<? endif; ?>

	<? if ($_SERVER['SERVER_NAME'] == 'vk.xnova.su'): ?>
		<script src="//vk.com/js/api/xd_connection.js" type="text/javascript"></script>
		<script type="application/javascript">
			$(window).load(function()
			{
				  VK.init(function() { console.log('vk init success'); }, function() {}, '5.24');
			});
		</script>
	<? endif; ?>

	<?
		if ($this->request->has('apiconnection') && (!$this->session->has('OKAPI') || !isset($this->session->get('OKAPI')['apiconnection'])))
		{
			$_SESSION['OKAPI'] = Array
			(
				'api_server' 			=> $this->request->get('api_server'),
				'apiconnection' 		=> $this->request->get('apiconnection'),
				'session_secret_key' 	=> $this->request->get('session_secret_key'),
				'session_key' 			=> $this->request->get('session_key'),
				'logged_user_id' 		=> $this->request->get('logged_user_id'),
				'sig' 					=> $this->request->get('sig')
			);
		}
	?>
	<? if (!$this->cookies->has($this->config->cookie->prefix.'_full') && $this->session->has('OKAPI') && is_array($this->session->get('OKAPI'))): ?>
		<script src="<?=$this->session->get('OKAPI')['api_server'] ?>js/fapi5.js" type="text/javascript"></script>
		<script type="text/javascript">
			FAPI.init('<?=$this->session->get('OKAPI')['api_server'] ?>', '<?=$this->session->get('OKAPI')['apiconnection'] ?>',
				function()
				{
					//FAPI.UI.setWindowSize(800, 700);
				}
				, function(error)
				{
					alert("API initialization failed");
				}
			);
		</script>
	<? endif; ?>

	<div id="windowDialog"></div>
	<div id="tooltip" class="tip"></div>

	<? if ((!isset($leftMenu) || $leftMenu == false)): ?>
		</center></div></div></div>
	<? endif; ?>

	</body>
</html>