<? if (isset($topPanel) && $topPanel == true): ?>
	<? $this->partial('shared/panel'); ?>
<? endif; ?>

<? if (isset($pageParams['deleteUserTimer']) && $pageParams['deleteUserTimer'] > 0): ?>
	<table class="table"><tr><td class="c" align="center">Включен режим удаления профиля!<br>Ваш аккаунт будет удалён после <?=$this->game->datezone("d.m.Y", $pageParams['deleteUserTimer']) ?> в <?=$this->game->datezone("H:i:s", $pageParams['deleteUserTimer']) ?>. Выключить режим удаления можно в настройках игры.</td></tr></table><div class="separator"></div>
<? endif; ?>

<? if (isset($pageParams['vocationTimer']) && $pageParams['vocationTimer'] > 0): ?>
   <table class="table"><tr><td class="c" align="center"><font color="red">Включен режим отпуска! Функциональность игры ограничена.</font></td></tr></table><div class="separator"></div>
<? endif; ?>

<? if (isset($pageParams['message']) && $pageParams['message'] != ''): ?>
   <table class="table"><tr><td class="c" align="center"><?=$pageParams['message'] ?></td></tr></table><div class="separator"></div>
<? endif; ?>

<div class="row">
	<?php echo $this->getContent() ?>
</div>

<? if ($userId > 0 && !$isPopup): ?>
	<? $this->view->partial('shared/planets_ajax'); ?>
<? endif; ?>

<? if (!$isPopup): ?>
	<script>document.title = "<?=str_replace("\n", "", $this->tag->getTitle(false)) ?>";</script>
<? endif; ?>

<? if ($this->game->checkSaveState()): ?>
	<script>addHistoryState("<?=$this->game->getClearQuery() ?>")</script>
<? endif; ?>

<? if (isset($ajaxNavigation) && $ajaxNavigation && $this->game->checkSaveState()): ?>
	<script type="text/javascript">setMenuItem("<?=($this->dispatcher->getControllerName().($this->dispatcher->getControllerName() == 'buildings' ? $this->dispatcher->getActionName() : '')) ?>");</script>
<? endif; ?>

<? if ($userId > 0): ?>
	<script type="text/javascript">UpdateGameInfo('<?=$messages ?>', '<?=$messages_ally ?>'); <? if (!$isPopup): ?>timestamp = <?=time() ?>;<? endif; ?></script>
<? endif; ?>