<?= $this->tag->getDoctype() ?>
<html lang="ru">
<head>
	<?php echo $this->tag->getTitle(); ?>
	<?= $this->tag->tagHtml('meta', ['name' => 'description', 'content' => '']) ?>
	<?= $this->tag->tagHtml('meta', ['name' => 'keywords', 'content' => '']) ?>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta name="viewport" content="width=device-width">

	<link rel="image_src" href="http://<?=$_SERVER['HTTP_HOST'] ?>/images/logo.jpg" />
	<link rel="apple-touch-icon" href="http://<?=$_SERVER['HTTP_HOST'] ?>/images/apple-touch-icon.png"/>

	<?php $this->assets->outputJs('headerJs') ?>
	<?php $this->assets->outputCss('headerCss') ?>
</head>
<body>
	<script type="text/javascript">
		var ajax_nav = 1;
		var addToUrl = '';
	</script>
	<?php echo $this->getContent() ?>
</body>
</html>