<?= $this->tag->getDoctype() ?>
<html lang="ru">
<head>
	<?php echo $this->tag->getTitle(); ?>
	<?= $this->tag->tagHtml('meta', ['name' => 'description', 'content' => '']) ?>
	<?= $this->tag->tagHtml('meta', ['name' => 'keywords', 'content' => '']) ?>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<meta name="viewport" content="width=device-width">

	<link rel="image_src" href="//<?=$_SERVER['HTTP_HOST'] ?>/assets/images/logo.jpg" />
	<link rel="apple-touch-icon" href="//<?=$_SERVER['HTTP_HOST'] ?>/assets/images/apple-touch-icon.png"/>

	<?php $this->assets->outputCss('css') ?>
	<?php $this->assets->outputJs('js') ?>

	<!--[if lte IE 9]>
		<link rel="stylesheet" href="https://rawgit.com/codefucker/finalReject/master/reject/reject.css" media="all" />
		<script type="text/javascript" src="https://rawgit.com/codefucker/finalReject/master/reject/reject.min.js"></script>
	<![endif]-->
</head>
<body>
	<script type="text/javascript">
		var ajax_nav = 1;
		var addToUrl = '';
	</script>
	<?php echo $this->getContent() ?>
</body>
</html>