<table class="table">
	<tr>
		<td class="c" width="100">Дата</td>
		<td class="c">Новости</td>
	</tr>
	<? foreach ($history AS $hash => $news): ?>
	<tr>
		<th width="70"><?=$news['date'] ?></th>
		<td style="text-align:left" class="b">
			<font color="lime"><?=$news['author'] ?></font>
			<br>
			<?=$news['message'] ?>
			<br><br>
			Commit hash <a href="https://gitlab.com/alexprowars/xnova-uni5/commit/<?=$hash ?>/" target="_blank"><?=$hash ?></a>
		</td>
	</tr>
	<? endforeach; ?>
</table>