<?
/**
 * @var $parse array
 */
?>
<div class="block">
	<div class="title">
		<?=$parse['off_points'] ?> <?=$parse['alv_points'] ?>
	</div>
	<div class="content container-fluid officiers">
		<div class="row">
			<div class="hidden-xs col-sm-2 text-center">
				<img src="/assets/images/officiers/bigcredits.jpg" alt="">
			</div>
			<div class="col-xs-12 col-sm-7 text-left">
				Кредиты (<a href="<?=$this->url->get('credits/') ?>"><span class="positive">Получить</span></a>)<br><br>Инженеры берут за свою работу только межгалактичесие кредиты. В зависимости от суммы контракта работают на вас в течении всего времени найма.
				<table class="powers">
					<tr>
						<td><img src="/assets/images/officiers/smalcredts.gif"></td>
						<td>При помощи кредитов можно нанять инженеров</td>
					</tr>
				</table>
			</div>
			<div class="col-sm-3 hidden-xs text-center">
				<a href="<?=$this->url->get('credits/') ?>" class="positive">Получить кредиты</a>
			</div>
		</div>
		<? foreach ($parse['list'] AS $list): ?>
			<div class="row">
				<div class="hidden-xs col-sm-2 text-center">
					<img src="/assets/images/officiers/<?=$list['off_id'] ?>.jpg" align="top" alt=""/>
				</div>
				<div class="col-xs-12 col-sm-7 text-left">
					<font color="#ff8900"><?=$list['off_tx_lvl'] ?> (<?=$list['off_lvl'] ?>)</font>
					<br><br>
					<?=$list['off_desc'] ?>
					<table class="powers">
						<tr>
							<td rowspan="<?=(count($list['off_powr']) + 1) ?>"><img src="/assets/images/officiers/<?=$list['off_id'] ?>.gif"></td>
						</tr>
						<? foreach ($list['off_powr'] as $power): ?>
							<tr><td class="up"><?=$power ?></td></tr>
						<? endforeach; ?>
					</table>
				</div>
				<div class="clearfix visible-xs"><div class="separator"></div></div>
				<div class="col-xs-6 visible-xs text-center">
					<img src="/assets/images/officiers/<?=$list['off_id'] ?>.jpg" align="top" alt=""/>
				</div>
				<div class="col-xs-6 col-sm-3 text-center">
					<form method="POST" action="<?=$this->url->get('officier/') ?>"><?=$list['off_link'] ?></form>
				</div>
			</div>
		<? endforeach; ?>
	</div>
</div>